# _config.yml
title: Max Mustermann
description: Personal Website / CV
baseurl: ""           # leer f√ºr root deployment
url: "https://username.github.io"  # dein GitHub Pages URL
theme: minimal-mistakes-jekyll    # Beispiel: beliebtes One-Pager/Portfolio Theme
