# _config.yml
title: Max Mustermann
description: Personal Website / CV
baseurl: ""           # leer f√ºr root deployment
url: "https://ecklex.github.io"  # dein GitHub Pages URL

# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
