# _config.yml
title: Alexander Eckerlin
description: Personal Website & CV – Alexander Eckerlin, Publisher
author: Alexander Eckerlin
lang: de
baseurl: ""           # leer für root deployment
url: "https://ecklex.github.io"  # dein GitHub Pages URL

# Theme
theme: jekyll-theme-cayman
