# _config.yml
title: Max Mustermann
description: Personal Website / CV
baseurl: ""           # leer f√ºr root deployment
url: "https://ecklex.github.io"  # dein GitHub Pages URL
remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: default

plugins:
  - jekyll-include-cache
